### ISSUE TITLE
installation of dependency igraph fails on MacOs Ventura 13.4.1.

### ISSUE THREAD

**Issue by thomasalcock** [Dschaykib/codeAnalyseR#1]
<img width="1694" alt="Bildschirmfoto 2024-06-03 um 09 58 09" src="https://github.com/Dschaykib/codeAnalyseR/assets/49150460/0314a00a-478f-4b3c-8e95-651624b936b2">

**Comment by sw-jakobgepp** [comment]
is it possible to install igraph manually?

**Comment by thomasalcock** [comment]
The build from source fails, according to this thread https://stackoverflow.com/questions/68248503/failing-to-install-igraph-package-in-r#comment120620903_68248503 a binary install should work, but also fails for version 2.0.3

**Comment by thomasalcock** [comment]
It failed to R version 3.6.2, after upgrading to 4.4.0 I was able to install it.

**Comment by szhorvat** [comment]
The troubleshooting document at https://r.igraph.org/articles/installation-troubleshooting.html should answer all your installation questions. The StackOverflow thread you linked is outdated and no longer relevant.
